// Revenue Fluent — Service Worker
// Version: 2026-08-17
// Enables offline access and PWA install
const CACHE_NAME = 'revenue-fluent-v17';
const CORE_FILES = [
  '/',
  '/index.html',
  '/home.html',
  '/scenario-library.html',
  '/scenarios.html',
  '/simulate.html',
  '/upload.html',
  '/profile.html',
  '/myorg.html',
  '/downloads.html',
  '/learn.html',
  '/pricing.html',
  '/privacy.html',
  '/terms.html',
  '/humacity.html',
  '/p1-tool.html',
  '/p2-tool.html',
  '/p3-tool.html',
  '/p4-tool.html',
  '/p5-tool.html',
  '/shared.js',
  '/rf-data.js',
  '/rf-export.js',
  '/rf-report.js',
  '/rf-report.css',
  '/rf-profile.js',
  '/rf-onboarding.js',
  '/rf-org.js',
  '/manifest.json',
  '/favicon.png',
  '/logo.png',
];
